### ISSUE TITLE
Feature: Adding additional information to TSR Title

### ISSUE THREAD

**Issue by Alanin** [Pavion/TsrPlugin#1]
Hi,

It would be nice to have the information about the Subtitle of the recorded item in the title/filename of the recording in TSR itself. Maybe it is also possible to have the information about the season and episode in the filename as well, as long they are provided in TV-Browser.

For example the recording in TSR would be named like 

The Big Bang Theory - Die Beischlaf-Vermutung.ts or
The Big Band Theory - S02E01 - Die Beischlaf-Vermutung.ts

But I think the information bout the season and episode is mostly missing in TV-Browser data. But having the Episode Title in the recording would be really great.

Thank you alot
Alanin

**Comment by Pavion** [comment]
Hallo Alanin,

thank you for your feedback! Please check the newest release here:
https://github.com/Pavion/TsrPlugin/releases/tag/1.0.3.1

Best regards
Pav

**Comment by Alanin** [comment]
Wow that’s great, thank you a lot. Going to test it later and going to give feedback. 

Alanin

**Comment by Alanin** [comment]
Hallo Pav,

it works great! Thank you again!

Alanin
