### ISSUE TITLE
Recording names with ampersand (&) characters are truncated in TSR

### ISSUE THREAD

**Issue by cjaone** [Pavion/TsrPlugin#2]
Recording names with ampersand symbols are truncated in TSR because they are not URL encoded by the TSR plugin before it sends the HTTP request.

**Example:**

- Try to record the show _**"Shakespeare & Hathaway - Private Investigators"**_ with TVBrowser (or any other show which includes the ampersand character)

**Result:**

- TSR plugin sends the HTTP request with the following parameters:

recname=Shakespeare & Hathaway - Private Investigators&sender=ZDFneo&von=20:15&bis=20:55&am=2023-02-10&uniqueid=tvbrowserdataservice.TvBrowserDataService_digital_de_zdfneo_2023-02-10_20:15:60

- TSR recording name will be _**"Shakespeare "**_ only because the recname ends at the next ampersand (&) character

**Comment by Pavion** [comment]
Thanks for reporting, should be fixed now. You can download the latest release from this page or via TV-Browser.
